93 fix proposal python examples
vegaprotocol/sample-api-scripts pull request #94
Opened 2021-12-13 11:50 UTC by wwestgarth

closes #93

2021-12-13 13:35 UTC, edd approved these changes

2021-12-13 13:36 UTC, edd commented
Thanks @wwestgarth , looking good :+1: 

My Python is bad so this isn't an in depth code review, but working is better than broken.

2021-12-14 11:28 UTC, candida-d requested changes
Thanks for adding & updating these, Will! I spotted a few things that don't seem relevant for freeform gov proposals, so I've highlighted them.

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/README.md
> +# Sample API scripts - Propose Markets
```suggestion
# Sample API scripts - Propose Freeform Proposal
```

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    vote_asset_id = next((x["id"] for x in assets if x["details"]["symbol"] == "tVOTE"), None)
tVOTE is gone now, it's VEGA (testnet) - but maybe it should just be 'VEGA' so it's applicable to non-testnet too

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +        print("tVOTE asset not found on specified Vega network, please symbol name check and try again")
(here too)

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +        print(f"Please deposit tVOTE asset to public key {pubkey} and try again")
```suggestion
        print(f"Please deposit VEGA asset to public key {pubkey} and try again")
```

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    # __prepare_propose_updateNetworkParameter:
I'm not sure if this section needs renaming or if it can go completely, but as it's about network parameter proposals it should change

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    # Compose a governance proposal for updating a network parameter
```suggestion
    # Compose a freeform governance proposal 
```

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    # Set closing/enactment and validation timestamps to valid time offsets
Is enactment time right for freeform? (Sorry - can't remember which of the times specifically aren't relevant for this type)

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    # Sign the network param update proposal transaction
```suggestion
    # Sign the proposal transaction
```

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    print("Signed market proposal and sent to Vega")
```suggestion
    print("Signed proposal and sent to Vega")
```

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    #                              F I N D   A S S E T S                                #
Pretty sure this 'find assets' section can be deleted for a freeform proposal

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +                    "description": "A short description of the propsals",
```suggestion
                    "description": "A short description of the proposals",
```

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    # STEP 2 - Let's vote on the market proposal
```suggestion
    # STEP 2 - Let's vote on the proposal
```

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    # YES vote from the proposer will not be enough to vote the market into existence.
```suggestion
    # YES vote from the proposer will not be enough to vote the proposal into existence.
```

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    # threshold for market proposals this is currently a 66% majority vote either YES or NO.
```suggestion

```

2021-12-14 11:28 UTC, candida-d commented on propose-freeform/propose-vote-enact-freeform.py
> +    # This is because of the network minimum threshold for voting on proposals, this
```suggestion
    # This is because of the network minimum threshold for voting on proposals.
```

2021-12-14 11:28 UTC, candida-d commented on propose-netparams/README.md
> +# Sample API scripts - Propose Markets
```suggestion
# Sample API scripts - Propose Network Parameter Change
```

2021-12-14 11:28 UTC, candida-d commented on propose-netparams/propose-vote-enact-netparams.py
> +# YES vote from the proposer will not be enough to vote the market into
```suggestion
# YES vote from the proposer will not be enough to vote the proposal in.
```

2021-12-14 11:28 UTC, candida-d commented on propose-netparams/propose-vote-enact-netparams.py
> +# existence. As described above in STEP 2, a netparam change will need community voting
```suggestion
# As described above in STEP 2, a network parameter change will need community voting
```

2021-12-15 18:41 UTC, candida-d approved these changes

2021-12-16 13:46 UTC, merged