97 fix python api client examples
vegaprotocol/sample-api-scripts pull request #98
Opened 2021-12-21 14:55 UTC by wwestgarth

closes #97 

Almost all the changes are just due to the protos having shuffled around after the data node split.

2021-12-21 15:36 UTC, edd commented on submit-amend-cancel-orders/submit-amend-cancel-orders-with-Vega-API-client.py
> +orderTif = helpers.enum_to_str(vac.vega.veag.Order.TimeInForce, response.order.time_in_force)
```suggestion
orderTif = helpers.enum_to_str(vac.vega.vega.Order.TimeInForce, response.order.time_in_force)
```

2021-12-21 15:37 UTC, edd approved these changes
Approved, as long as you accept my typo fix!

2021-12-21 19:45 UTC, candida-d commented on README.md
> +| Propose, vote and enact netparam update | python3 | Vega node [REST] | / [propose-markets](propose-netparam) |
```suggestion
| Propose, vote and enact network parameters update | python3 | Vega node [REST] | / [propose-markets](propose-netparam) |
```

2021-12-21 19:53 UTC, candida-d commented on submit-order/submit-order-with-Vega-API-client.py
> +print("Signed pegged order and sent to Vega")
Question - is this a pegged order?

2021-12-21 19:55 UTC, candida-d requested changes
I've made one suggested change - to spell out network parameters, and asked a question about one console output. Thanks for making these changes Will!

2022-01-05 13:07 UTC, wwestgarth commented on submit-order/submit-order-with-Vega-API-client.py
> +print("Signed pegged order and sent to Vega")
Nope. Updated.

2022-01-05 13:26 UTC, candida-d approved these changes
LGTM!

2022-01-05 13:29 UTC, merged